environment:
  access_token:
    secure:
      jsPv246qH9Lwg0FuzMy7rlz/TU+1tFaHKVEgRn/aG22kJ7MoBTXyvQaPrOL3EnHV
  matrix:
    - job_name: Windows-MSVC
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      APP_NAME: win
    - job_name: Linux-Clang
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CXX: clang++
      CC: clang
      APP_NAME: linux-clang
      ENABLE_STATIC_ANALYSIS: ON
    - job_name: Linux-GCC
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CXX: g++-10
      CC: gcc-10
      APP_NAME: linux-gcc
    - job_name: MacOS-Clang
      APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APP_NAME: macos


version: '1.0.{build}'
skip_tags: true
clone_folder: /tmp/source

cache:
  - /home/appveyor/.hunter/_Base/Cache/
  - /home/appveyor/.hunter/_Base/Cellar/
  - C:/.hunter/_Base/Cache/
  - C:/.hunter/_Base/Cellar/
  - /Users/appveyor/.hunter/_Base/Cache/
  - /Users/appveyor/.hunter/_Base/Cellar/

build_script:
  - sh: >-
      mkdir build
      &&
      cd build
      &&
      cmake /tmp/source -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCI=${CI} -DBUILD_VERSION=${appveyor_build_version} -DENABLE_STATIC_ANALYSIS=${ENABLE_STATIC_ANALYSIS}
      &&
      cmake --build . --config "RelWithDebInfo"
      &&
      pwd && ls -l && ls -l output/*

for:
  - ######################## (MacOS)
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave

    init:
      # For AppVeyor's cache support
      - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install p7zip
      -
    artifacts:
      - path: build
        name: $(APP_NAME)

  - ######################## (Clang)
    matrix:
      only:
        - job_name: Linux-Clang

    install:
      # Static analysers
      - sh: sudo apt-get update && sudo apt-get install -y g++-10 g++-9 clang-tidy-10 cppcheck

    artifacts:
      - path: build
        name: $(APP_NAME)

  - ######################## (G++)
    matrix:
      only:
        - job_name: Linux-GCC

    install:
      # update because default is too old
      - sh: sudo apt-get update && sudo apt-get install -y g++-10 g++-9

    artifacts:
      - path: build
        name: $(APP_NAME)

  - ######################## (Windows)
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    clone_folder: c:\projects\source

    build_script:
      - cmd: >-
          mkdir build

          cd build

          cmake c:\projects\source -G "Visual Studio 16 2019" -DCI=%CI% -DBUILD_VERSION=%APPVEYOR_BUILD_VERSION%

          cmake --build . --config "RelWithDebInfo"

          move output\RelWithDebInfo\*.pdb .\

          move output\RelWithDebInfo\*.* output\

    artifacts:
      - path: build\*.pdb
        name: win_pdb
      - path: build\output
        name: $(APP_NAME)
        type: zip

after_build:
  - git config --global credential.helper store
  - ps: Add-Content -Path "$HOME/.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - git config --global user.email "samuel.lacroix1@gmail.com"
  - git config --global user.name "Samuel Lacroix"
  - cmd: git push --delete origin latest-%APP_NAME% & SET ERRORLEVEL=0
  - sh: git push --delete origin latest-${APP_NAME} || true

deploy:
  - provider: GitHub
    auth_token: $(access_token)
    tag: latest-$(APP_NAME)
    release: latest-$(APP_NAME)
    artifact: /.*/
    draft: false
    prerelease: false
    force_update: true
    on:
      branch: master
