environment:
  matrix:
    - job_name: Linux-Clang
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CXX: clang++
      CC: clang
      APP_NAME: clang
      ENABLE_STATIC_ANALYSIS: ON
    - job_name: Linux-GCC
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      CXX: g++-10
      CC: gcc-10
      APP_NAME: gcc
    - job_name: Windows-MSVC
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      APP_NAME: win
    - job_name: MacOS-Clang
      APPVEYOR_BUILD_WORKER_IMAGE: macOS
      APP_NAME: macos

version: '1.0.{build}'

clone_folder: /tmp/source

cache:
  - /home/appveyor/.hunter/_Base/Cache/
  - /home/appveyor/.hunter/_Base/Cellar/
  - C:/.hunter/_Base/Cache/
  - C:/.hunter/_Base/Cellar/
  - /Users/appveyor/.hunter/_Base/Cache/
  - /Users/appveyor/.hunter/_Base/Cellar/

build_script:
  - sh: >-
      mkdir build
      &&
      cd build
      &&
      cmake /tmp/source -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo -DCI=${CI} -DBUILD_VERSION=${appveyor_build_version} -DENABLE_STATIC_ANALYSIS=${ENABLE_STATIC_ANALYSIS}
      &&
      cmake --build . --config "RelWithDebInfo"
      &&
      pwd && ls -l && ls -l output/*

artifacts:
  - path: build/output/*
    name: $(APP_NAME)

for:
  -
    matrix:
      only:
        - job_name: Linux-Clang

    install:
      - sh: sudo apt-get install -y clang-tidy-10 cppcheck

  -
    matrix:
      only:
        - job_name: Linux-GCC

    install:
      - sh: sudo apt-get install -y g++-10 g++-9

  -
    matrix:
      only:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    clone_folder: c:\projects\source

    build_script:
      - cmd: >-
          mkdir build

          cd build

          cmake c:\projects\source -G "Visual Studio 16 2019" -DCI=$(CI) -DBUILD_VERSION=$(appveyor_build_version)

          cmake --build . --config "RelWithDebInfo"

          del output\RelWithDebInfo\*.ilk

    artifacts:
      - path: build\output\RelWithDebInfo\*.*
        name: windows_x64
