image:
  - Visual Studio 2019
  - Ubuntu

for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    clone_folder: c:\projects\source

    build_script:
      - cmd: >-
          mkdir build

          cd build

          cmake c:\projects\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo

          cmake --build . --config "RelWithDebInfo"

          del output\RelWithDebInfo\*.ilk

    artifacts:
      - path: build\output\RelWithDebInfo\*.*
        name: windows_x64

  -
    matrix:
      only:
        - image: Ubuntu

    clone_folder: /tmp/source

    build_script:
      - sh: >-
          mkdir build

          cd build

          cmake /tmp/source -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo

          cmake --build . --config "RelWithDebInfo"


    artifacts:
      - path: build/output/*
        name: linux_x64